# Settings to access CROC Cloud using public API
export C2_PROJECT="vilyin"
export S3_URL="https://storage.cloud.croc.ru:443"
export EC2_URL="https://api.cloud.croc.ru:443"
export EKS_URL="https://eks.cloud.croc.ru:443"
export AWS_CLOUDWATCH_URL="https://monitoring.cloud.croc.ru:443"
export AWS_CLOUDTRAIL_URL="https://cloudtrail.cloud.croc.ru:443"
export EC2_ACCESS_KEY="${C2_PROJECT}:vilyin@cloud.croc.ru"
export EC2_SECRET_KEY="ZPhuMX1iQE6bchSp0weifw"
export AWS_ACCESS_KEY_ID="$EC2_ACCESS_KEY"
export AWS_SECRET_ACCESS_KEY="$EC2_SECRET_KEY"
